# Generated by Django 5.2.11 on 2026-02-11 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('AUTHORITY', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('Date', models.DateField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.CharField(max_length=100)),
                ('AUTHORITY', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Authority_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=100)),
                ('phoneNo', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('position', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Awareness_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('punishment', models.TextField()),
                ('date', models.DateField(max_length=100)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authority_table')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.FileField(upload_to='')),
                ('Email', models.CharField(max_length=100)),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('report_type', models.CharField(max_length=100)),
                ('Audio', models.FileField(upload_to='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('Authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authority_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
