# Generated by Django 5.2.11 on 2026-02-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='AUTHORITY',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='AUTHORITY',
        ),
        migrations.AlterField(
            model_name='awareness_table',
            name='authority',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.authority_table'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='authority',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.authority_table'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='authority',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.authority_table'),
        ),
    ]
