# Generated by Django 5.2.11 on 2026-02-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_complaint_authority_remove_complaint_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='awareness_table',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
